# Spring Boot configuration
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/serverdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true